name: Push Then Deploy

on:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Connect And Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSWORD }}
          script: |
            cd /opt/app
            ./refresh.sh pop
